const { Schema, model, Types } = require("mongoose");
const schema = new Schema({
  userId: { type: Types.ObjectId },
  a11: { type: String },
  a12: { type: String },
  a13: { type: String },
  a14: { type: String },
  a15: { type: String },
  a16: { type: String },
  a17: { type: String },
  a18: { type: String },
  a21: { type: String },
  a22: { type: String },
  a23: { type: String },
  a24: { type: String },
  a25: { type: String },
  a26: { type: String },
  a27: { type: String },
  a28: { type: String },
  a31: { type: String },
  a32: { type: String },
  a33: { type: String },
  a34: { type: String },
  a35: { type: String },
  a36: { type: String },
  a37: { type: String },
  a38: { type: String },
  a41: { type: String },
  a42: { type: String },
  a43: { type: String },
  a44: { type: String },
  a45: { type: String },
  a46: { type: String },
  a47: { type: String },
  a48: { type: String },
});

module.exports = model("ClientData", schema);
